POST http://localhost:3333/polls HTTP/1.1
content-type: application/json

{
    "title": "What is the best NodeJS framework",
    "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

###
GET http://localhost:3333/polls/63738fe3-732e-4257-915a-4f4b947863ce HTTP/1.1

###
POST http://localhost:3333/polls/63738fe3-732e-4257-915a-4f4b947863ce/vote HTTP/1.1
content-type: application/json

{
    "pollOptionId": "cf3a5eaa-c127-4b1a-b7d9-0da203277db0"
}