POST http://localhost:3333/polls HTTP/1.1
content-type: application/json

{
    "title": "What is the best NodeJS framework",
    "options": ["Express", "Fastify", "NestJS", "HapiJS"]
}

###
GET http://localhost:3333/polls/65553b77-c115-4c8c-985a-e4e5036f270a HTTP/1.1

###
POST http://localhost:3333/polls/65553b77-c115-4c8c-985a-e4e5036f270a/vote HTTP/1.1
Content-Type: application/json

{
    "pollOptionId": "dec85fee-5a5d-4474-9634-7b2494f083d5"
}